name: huazhongbei-b
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - scipy
  - matplotlib
  - pillow
  - scikit-image
  - jupyter
  - ipykernel
  - pip
  - pip:
      - opencv-python
